version: "3"
services:
    web:
        # replace username/repo:tag with your name and image details
        image: zstatmanweil/ej-analysis-map:web
        deploy:
            replicas: 5
            resources:
                limits:
                    cpus: "0.1"
                    memory: 50M
            restart_policy:
                condition: on-failure 
        ports:
            - "4000:8080"
        networks:
            - webnet
networks:
    webnet:
